import {
	FC,
	Fragment,
	useEffect,
	useState,
} from "react";

import {
	Paper,
	MenuList,
	ListItemText,
	ButtonGroup,
	Popover,
	MenuItem,
	ListItemIcon,
	Theme,
	useMediaQuery,
} from "@mui/material";
import {
	DownloadRounded,
	SendRounded,
} from "@mui/icons-material";
import { useSnackbar } from "notistack";

import {
	lexerGetAllTokens,
	lexerInit,
	DiagramNode,
	parserGetAllNodes,
	parserInit,
} from "core";

import { DiagramPreview } from "App/components/DiagramPreview";
import { StyledCodeEditor } from "App/components/StyledCodeEditor";
import { AdaptiveButton } from "App/components/AdaptiveButton";

import { Layout } from "./Layout";
import { useExportDiagram } from "./useExportDiagram";
import { useEditorContent } from "./useEditorContent";
import { generateUniqueLink } from "./helper";

/**
 * The main component of the application.
 * It defines the primary interface of the application, as well as the main logic.
 *
 * The layout is controlled by the "Layout" component.
 * The "StyledCodeEditor" component provides text editor.
 * The "DiagramPreview" component provides the diagram preview.
 */
export const LiveEditor: FC = () => {
	// Prepare the snackbar feedback functionality
	const { enqueueSnackbar } = useSnackbar();
	// Prepare the export functionality
	const { exportJPEG, exportPNG, exportSVG } =
		useExportDiagram(
			"structogram-preview-region",
		);
	// Prepare the editor content
	const { editorContent, setEditorContent } =
		useEditorContent(
			window.location.href,
			"autosaveContent",
		);
	const matchBreakpointXs = useMediaQuery<Theme>(
		(theme) => theme.breakpoints.down("md"),
	);

	// Stores the parsed nodes which will be sent to the diagram preview to render
	const [nodes, setNodes] = useState<
		DiagramNode[]
	>([]);
	// Stores the anchor element for the export menu popover
	const [
		popoverExportMenuAnchor,
		setPopoverExportMenuAnchor,
	] = useState<HTMLButtonElement | null>(null);

	// Fires when the editor content changes
	// Signals the lexer and parser to re-parse the content
	// One issue is that the entire abstract syntax tree is re-parsed on every keystroke
	// This is not ideal, but it is a simple solution for now
	useEffect(() => {
		const tokens = lexerGetAllTokens(
			lexerInit(editorContent),
		);
		const nodes = parserGetAllNodes(
			parserInit(tokens),
		);
		setNodes(nodes);
	}, [editorContent]);

	// Fire when the "COPY LINK" button is clicked
	// The function writes the unique link to the clipboard
	// The unique link is generated by a helper function
	const handleCopyLink = () => {
		navigator.clipboard.writeText(
			generateUniqueLink(
				editorContent,
				window.location.href,
			),
		);
		// Signals a success message to the user
		enqueueSnackbar("Link copied to clipboard", {
			variant: "info",
		});
	};

	// Fires when the "EXPORT" button is clicked
	// The popover is displayed with the export options
	const handlePopoverExportMenuOpen = (
		event: React.MouseEvent<HTMLButtonElement>,
	) => {
		setPopoverExportMenuAnchor(
			event.currentTarget,
		);
	};

	// Fires when the export menu popover is closed or dismissed
	const handlePopoverExportMenuClose = () => {
		setPopoverExportMenuAnchor(null);
	};

	// Fires when an export option is selected
	const handleExportDiagram = async (
		exportCallback: () => Promise<boolean>,
	) => {
		exportCallback().then((success) => {
			if (success) {
				enqueueSnackbar("Diagram exported", {
					variant: "info",
				});
				return;
			}
			enqueueSnackbar(
				"Failed to export diagram",
				{
					variant: "error",
				},
			);
		});
	};

	return (
		<Fragment>
			<Layout
				slotAppBar={
					<ButtonGroup variant="outlined">
						<AdaptiveButton
							collapsed={matchBreakpointXs}
							startIcon={<DownloadRounded />}
							onClick={
								handlePopoverExportMenuOpen
							}
						>
							EXPORT
						</AdaptiveButton>
						<AdaptiveButton
							collapsed={matchBreakpointXs}
							endIcon={<SendRounded />}
							onClick={handleCopyLink}
						>
							SHARE
						</AdaptiveButton>
					</ButtonGroup>
				}
				slotPanelLeft={
					<StyledCodeEditor
						value={editorContent}
						onValueChange={setEditorContent}
					/>
				}
				slotPanelRight={
					<DiagramPreview
						nodes={nodes}
						id="structogram-preview-region"
						boxProps={{
							height: "100%",
							padding: 4,
							userSelect: "none",
						}}
					/>
				}
			/>
			<Popover
				anchorOrigin={{
					vertical: "bottom",
					horizontal: "left",
				}}
				transformOrigin={{
					vertical: "top",
					horizontal: "left",
				}}
				anchorEl={popoverExportMenuAnchor}
				open={popoverExportMenuAnchor !== null}
				onClose={handlePopoverExportMenuClose}
			>
				<Paper
					sx={{
						padding: 1,
					}}
				>
					<MenuList>
						<MenuItem
							onClick={() =>
								handleExportDiagram(exportJPEG)
							}
						>
							<ListItemIcon>
								<DownloadRounded fontSize="small" />
							</ListItemIcon>
							<ListItemText>
								Save as JPEG
							</ListItemText>
						</MenuItem>
						<MenuItem
							onClick={() =>
								handleExportDiagram(exportPNG)
							}
						>
							<ListItemIcon>
								<DownloadRounded fontSize="small" />
							</ListItemIcon>
							<ListItemText>
								Save as PNG
							</ListItemText>
						</MenuItem>
						<MenuItem
							onClick={() =>
								handleExportDiagram(exportSVG)
							}
						>
							<ListItemIcon>
								<DownloadRounded fontSize="small" />
							</ListItemIcon>
							<ListItemText>
								Save as SVG
							</ListItemText>
						</MenuItem>
					</MenuList>
				</Paper>
			</Popover>
		</Fragment>
	);
};
